#!/bin/sh

_bootstrap_mkdir(){
    mkdir -p \
        "${HOME}/.local/bin/" \
        "${HOME}/.local/home/" \
        "${HOME}/.local/share/" \
        "${HOME}/.local/src/" \
        "${HOME}/.local/var/" \
        "${HOME}/bin/"
}

_bootstrap_tpm(){
    S_TPM="${HOME}/.tmux/plugins/tpm"
    [ -d "${S_TPM}" ] && return 0
    [ -e "${HOME}/.tmux.conf" ] || return 0
    git clone --depth=1 'https://github.com/tmux-plugins/tpm.git' "${S_TPM}"
    [ -n "${TMUX}" ] && return 0
    "${S_TPM}/bin/install_plugins"
}

_bootstrap_vim(){
    if ! command -v 'vim' >/dev/null 2>&1; then
        return 0
    fi
    if [ ! -f "${HOME}/.vim/autoload/plug.vim" ] ; then
        curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
          'https://raw.githubusercontent.com/junegunn/vim-plug/359ce90b9b37442974fd3ccd9279493d85efb3af/plug.vim'
    fi
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
}

set -eu

_bootstrap_mkdir
_bootstrap_tpm
_bootstrap_vim
