#!/bin/sh
# Feeling a bit lazy right now...
# shellcheck disable=SC2086
# shellcheck disable=SC2012

apt_get_update_maybe() {
    # shellcheck disable=SC2012
    if [ ! -d "/var/lib/apt/lists" ] || [ "$(ls /var/lib/apt/lists/ | wc -l)" = "0" ]; then
        apt-get update
    fi
}

apt_get_install_0() {
    # From vscode common-debian
    PACKAGE_LIST="apt-utils \
        git \
        openssh-client \
        gnupg2 \
        iproute2 \
        procps \
        lsof \
        htop \
        net-tools \
        psmisc \
        curl \
        wget \
        rsync \
        ca-certificates \
        unzip \
        zip \
        nano \
        vim-tiny \
        less \
        jq \
        lsb-release \
        apt-transport-https \
        dialog \
        libc6 \
        libgcc1 \
        libkrb5-3 \
        libgssapi-krb5-2 \
        libicu[0-9][0-9] \
        liblttng-ust0 \
        libstdc++6 \
        zlib1g \
        locales \
        sudo \
        ncdu \
        man-db \
        strace"

    apt-get -y install \
        --no-install-recommends ${PACKAGE_LIST}
}

apt_get_install_1(){
    # From vscode common-debian
    PACKAGE_LIST="yadm \
        vim \
        tmux \
        "

    apt-get -y install \
        --no-install-recommends ${PACKAGE_LIST}
}

useradd_user(){
    if [ -z "${USERNAME}" ]; then
        return 0
    fi
    USER_UID=${USER_UID:-"automatic"}
    USER_GID=${USER_GID:-"automatic"}

    # Create or update a non-root user to match UID/GID.
    if id -u ${USERNAME} > /dev/null 2>&1; then
        # User exists, update if needed
        if [ "${USER_GID}" != "automatic" ] && [ "$USER_GID" != "$(id -G $USERNAME)" ]; then
            groupmod --gid $USER_GID $USERNAME
            usermod --gid $USER_GID $USERNAME
        fi
        if [ "${USER_UID}" != "automatic" ] && [ "$USER_UID" != "$(id -u $USERNAME)" ]; then
            usermod --uid $USER_UID $USERNAME
        fi
    else
        # Create user
        if [ "${USER_GID}" = "automatic" ]; then
            groupadd $USERNAME
        else
            groupadd --gid $USER_GID $USERNAME
        fi
        if [ "${USER_UID}" = "automatic" ]; then
            useradd -s /bin/bash --gid $USERNAME -m $USERNAME
        else
            useradd -s /bin/bash --uid $USER_UID --gid $USERNAME -m $USERNAME
        fi
    fi

}

################################################################################

_bootstrap_mkdir(){
    mkdir -p \
        "${HOME}/.local/bin/" \
        "${HOME}/.local/home/" \
        "${HOME}/.local/share/" \
        "${HOME}/.local/src/" \
        "${HOME}/.local/var/" \
        "${HOME}/bin/"
}

_bootstrap_apts(){
    if ! command -v 'sudo' >/dev/null 2>&1; then
        return 0
    fi
    if ! command -v 'rg' >/dev/null 2>&1; then
        sudo apt-get install ripgrep
    fi

    # TODO: Split graphical apps
    # if ! command -v 'barrier' >/dev/null 2>&1; then
    #     sudo apt-get install barrier
    # fi
    # # sudo apt-get -y install
    # sudo apt-get -y install --no-install-recommends \
    #     gir1.2-spiceclientgtk-3.0 \
    #     spice-client-gtk \
    #     virt-manager \
    #     virt-viewer
}

_bootstrap_snaps(){
    if ! command -v 'sudo' >/dev/null 2>&1; then
        return 0
    fi
    if ! command -v 'snap' >/dev/null 2>&1; then
        return 0
    fi
    if ! command -v 'nvim' >/dev/null 2>&1; then
        sudo snap install nvim
    fi
    if ! command -v 'joplin-desktop' >/dev/null 2>&1; then
        sudo snap install joplin-desktop
    fi
    if ! command -v 'code' >/dev/null 2>&1; then
        # code classic  Code editing. Redefined.
        sudo snap install --classic code
    fi
    # if ! command -v 'rg' >/dev/null 2>&1; then
    #     sudo snap install ripgrep
    # fi
}

_bootstrap_tpm(){
    S_TPM="${HOME}/.tmux/plugins/tpm"
    [ -d "${S_TPM}" ] && return 0
    git clone --depth=1 'https://github.com/tmux-plugins/tpm.git' "${S_TPM}"
    if [ -n "${TMUX}" ] ; then
        echo "TODO: Handle existing tmux session"
        return 1
    fi
    "${S_TPM}/bin/install_plugins"
}

_bootstrap_vim(){
    if ! command -v 'vim' >/dev/null 2>&1; then
        return 0
    fi
    if [ ! -f "${HOME}/.vim/autoload/plug.vim" ] ; then
        curl -fLo "${HOME}/.vim/autoload/plug.vim" --create-dirs \
          'https://raw.githubusercontent.com/junegunn/vim-plug/359ce90b9b37442974fd3ccd9279493d85efb3af/plug.vim'
    fi
    vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
}

_bootstrap_spf13vim(){
    if ! command -v 'vim' >/dev/null 2>&1; then
        return 0
    fi
    if [ ! -e "${HOME}/.vimrc.bundles.local" ] ; then
        # https://github.com/spf13/spf13-vim/pull/1035
        echo "UnBundle 'amirh/HTML-AutoCloseTag'" >> .vimrc.bundles.local
    fi
    mkdir -p "${HOME}/.config/nvim/"
    if [ ! -d "${HOME}/.spf13-vim-3" ] ; then
        curl 'https://j.mp/spf13-vim3' -L > .spf13-vim.sh && sh spf13-vim.sh
    fi
    ln -frst "${HOME}/.config/nvim/" "${HOME}/.spf13-vim-3/.vimrc"
    ln -frst "${HOME}" "${HOME}/.spf13-vim-3/.vimrc" "${HOME}/.spf13-vim-3/.vimrc.before" "${HOME}/.spf13-vim-3/.vimrc.bundles"
}

_bootstrap_python3(){
    if ! command -v 'sudo' >/dev/null 2>&1; then
        return 0
    fi
    # TODO: Avoid require sudo
    # [python__base_packages3](https://docs.debops.org/en/stable-2.2/ansible/roles/python/defaults/main.html#python-3-management)
    sudo apt-get -y install \
        'python3-httplib2' 'python3-pip' 'python3-setuptools' 'python3-pycurl' \
        'python3-future' 'python3-virtualenv' 'python3-wheel' 'virtualenv'
}

_bootstrap_nvim(){
    if ! command -v 'nvim' >/dev/null 2>&1; then
        return 0
    fi
    nvim_dir="${HOME}/.config/nvim/"
    if [ ! -f "${HOME}/.config/nvim/Makefile" ] ; then
	if ! yadm submodule update --init --recursive ; then
		return 1
	fi
    fi
    cd "${nvim_dir}"

    pip3 install --user pynvim
    pip3 install --user PyYAML
    pip3 install --user vim-vint pycodestyle pyflakes flake8

    make test
    make
}

_bootstrap_yadm(){
    if [ -d "$HOME/.local/share/yadm/repo.git" ] ; then
        return 0
    fi
    if [ -d "$HOME/.yadm/repo.git" ] ; then
        return 0
    fi

    yadm clone "${YADM_SRCURI}"
    yadm remote set-url origin --push none
}

################################################################################

_bootstrap_user(){
    # _bootstrap_yadm
    _bootstrap_mkdir

    # _bootstrap_tpm

    # NOTE: Only one of these should be enabled
    _bootstrap_spf13vim
    # _bootstrap_vim
    _bootstrap_nvim
}

_bootstrap_root(){
    apt_get_update_maybe
    apt_get_install_0
    apt_get_install_1

    _bootstrap_apts # NOTE: Require sudo.
    _bootstrap_snaps

    _bootstrap_python3

    useradd_user
    # _bootstrap_yadm

    # TODO
    #update-alternatives --set editor "$(which nvim)"
    # TODO
    #locale.gen
}

_bootstrap(){
    if [ "$(id -u)" -ne 0 ]; then
        _bootstrap_user
    else
        _bootstrap_root
    fi
}

################################################################################

YADM_SRCURI="${YADM_SRCURI-https://home.genetzky.us}"

set -eu
_bootstrap
