all:
  hosts:
    localhost:
      ansible_ssh_host: localhost
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"

debops_all_hosts:
  hosts:
    localhost:
