#!/bin/bash

sudo_maybe()
{
    if [ "$(id -u)" -ne 0 ]; then
        sudo "$@"
    else
        "$@"
    fi
}

ssh_import_id_and_start_ssh(){
    _SSH_IMPORT_ID_USER='gh:ngenetzky'
    SSH_IMPORT_ID_USER="${SSH_IMPORT_ID_USER-${_SSH_IMPORT_ID_USER}}"

    sudo_maybe apt update && sudo_maybe apt install -y ssh-import-id ssh
    ssh-import-id gh:ngenetzky
    sudo_maybe service ssh start
}

debops_install_via_pip_and_apt(){
    sudo_maybe apt-get -q update \
        && DEBIAN_FRONTEND=noninteractive sudo_maybe apt-get \
        --no-install-recommends -yq install \
        iproute2 \
        iputils-ping \
        levee \
        openssh-client \
        python3-apt \
        python3-distro \
        python3-dnspython \
        python3-future \
        python3-ldap \
        python3-pip \
        python3-wheel \
        python3-setuptools \
        python3-cryptography \
        procps \
        sudo \
        tree \
        && pip3 install \
            debops[ansible]==2.2.2 \
        && echo "Cleaning up cache directories..." \
        && sudo_maybe rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*.deb /root/.cache/*
}

set -eu
ssh_import_id_and_start_ssh
debops_install_via_pip_and_apt
